name: CI

on: push

jobs:

  test-ubuntu:
  
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'
          
      - name: Test circle
        run: python -m unittest circle.py
        
      - name: Test square
        run: python -m unittest square.py
        
      - name: Test rectangle
        run: python -m unittest rectangle.py
        
      - name: Test triangle
        run: python -m unittest triangle.py
          
  test-windows:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'
          
      - name: Test circle
        run: python -m unittest circle.py
        
      - name: Test square
        run: python -m unittest square.py
        
      - name: Test rectangle
        run: python -m unittest rectangle.py
        
      - name: Test triangle
        run: python -m unittest triangle.py
